### ISSUE TITLE
Some chue scripts don't handle errors

### ISSUE THREAD

**Issue by sanderploegsma** [WISVCH/florriebot#88]
De Hue bridge was blijkbaar eerder deze week losgekoppeld, maar florrie reageert bij sommige commando's doodleuk alsnog met een ok. Het lijkt me logischer om eerst te checken of je request daadwerkelijk is uitgevoerd, voordat wordt gereageerd met 'oke man!'. (Sommige functies checken op `status == 200`, die doen het goed. Al lijkt het me alsnog leuk als er anders aangegeven wordt dat er iets mis gaat).

**Comment by praseodym** [comment]
Omdat het via chue gaat kunnen we de afhandeling daarin ook verbeteren, b.v. nette error string teruggeven die florrie dan kan posten. (Disclaimer: niet gecheckt wat er nu in chue gebeurt als de bridge er uit ligt)
